### PR TITLE
Dynamic & Decentralized Reputation for the Web of Trust: What We Can Learn from the World of Sports, Tinder, and Netflix

### PR DESCRIPTION
**Pull request by ankurdotb**

### CODE REVIEW

**Comment by elenachachkarova** [comment]
@ankurdotb, thank you for your submission.

**Comment by elenachachkarova** [comment]
@ankurdotb, we sent a promo code to Sietse Ringers, as an author of one of the papers you committed, could you provide an email to send you a code as well. Thank you.

**Comment by ankurdotb** [comment]
@elenachachkarova Oh I think that other entry was just when I rebased my branch to be able to submit without merge conflicts, Sietse Rogers is a separate contributor. Could you please send my code to [5lijfl7l@duck.com](mailto:5lijfl7l@duck.com)?

**Comment by ankurdotb** [comment]
Hi @elenachachkarova, I still haven't received a code for Eventbrite. Are you still okay to send this over?

**Pull request merged**
